;
; global custom
;
[custom]
build_flags =
  ${KNX_TP.build_flags}
  -D KNX_FLASH_SIZE=0 #Setting not used because partion knx is used, but must be defined
  -I lib/OGM-HardwareConfig/include/
  -D OPENKNX_DUALCORE
;  -D OPENKNX_LEDFUNC_BASE_PROG_UNCONFIGUREDSUPPORT
lib_deps =
    https://github.com/Seeed-Studio/PN532#2c47f5c836af53158c4e29685551612181fd8f9b
    madhephaestus/ESP32Encoder@0.12.0
  
[custom_develop]
; extends = custom
; build_flags =
;   ${custom.build_flags}
;   -D DEVELOPMENT
;   ;-D OPENKNX_SONOS_DEBUG
;   ;-D OPENKNX_HEARTBEAT
;   ; -D OPENKNX_HEARTBEAT_PRIO
;   ; -D OPENKNX_RTT
;   ; -D BUFFER_SIZE_UP=10240
;   ; -D DEBUG_LOOP_TIME=10 ; will print a info when a loop took more than x ms.
;   ; -D LOGIC_TRACE
;   ; ; to see trace logs, they must match one of the 5 filters (TRACE_LOG1 .. TRACE_LOG2)
;   ;"-D OPENKNX_TRACE1=OTAUpdateModule.*"
;   ;"-D OPENKNX_TRACE2=Flash.*"
; debug_build_flags = -ggdb3
;   -O0

; ^^^^Need to much memory ^^^^
extends = ESP32_releases, custom, custom_ESP32
build_flags =
  ${ESP32_releases.build_flags}
  ${custom.build_flags}
  ${custom_ESP32.build_flags}
  -D OPENKNX_LOOPTIME_WARNING=10
  -D DEVELOPMENT
  -D OPENKNX_DEBUG


; ESP32
[custom_ESP32]
extends = ESP32, custom
build_flags =
  ${ESP32.build_flags}
  -D SERIAL_DEBUG=Serial
  -D KNX_FLASH_CALLBACK
build_unflags =
  -D LWIP_DONT_PROVIDE_BYTEORDER_FUNCTIONS


[custom_release_ESP32]
extends = ESP32_releases, custom, custom_ESP32
build_flags =
  ${ESP32_releases.build_flags}
  ${custom.build_flags}
  ${custom_ESP32.build_flags}
  -D OPENKNX_LOOPTIME_WARNING=10



[PN532_SPI] # PN532 connected over SPI
build_flags =
  -D NFC_INTERFACE_SPI
  -D PN532_CS=5
  -D PN532_MISO=19
  -D PN532_MOSI=23
  -D PN532_SCK=18

[PN532_HSU] # PN532 connected over SERIAL
build_flags =
  -D NFC_INTERFACE_HSU
  -D PN532_RX=18
  -D PN532_TX=19

[PN532_I2C] # PN532 connected over I2C
build_flags =
  -D NFC_INTERFACE_I2C
  -D PN532_SDA=16
  -D PN532_SCL=17

; ------ ESP32 DevBoard ------
[board_ESP32_Sonos_NFC_Player]
build_flags =
  -D DEVICE_NAME=\"ESP32\x20Sonos\x20NFC\x20Player\"
  -D DEVICE_ID=\"ESP32-SONSO-NFC-PLAYER\"
  -D SERIAL_DEBUG=Serial
 # -D PN532_RSTPDN=26 # Used to reset the PN532
  -D OPENKNX_LEDEFFECT_PULSE_MIN=85
  -D PROG_LED_PIN=2
  -D PROG_LED_PIN_ACTIVE_ON=HIGH
  -D INFO1_LED_PIN=13
  -D INFO1_LED_PIN_ACTIVE_ON=HIGH
  -D INFO2_LED_PIN=12
  -D INFO2_LED_PIN_ACTIVE_ON=HIGH
  -D INFO3_LED_PIN=27
  -D INFO3_LED_PIN_ACTIVE_ON=HIGH
  -D PROG_BUTTON_PIN=0
  -D ENCODER1_CLK=32 
  -D ENCODER1_DT=33  
  -D ENCODER1_BUTTON=21 
  -D ENCODER2_CLK=34 
  -D ENCODER2_DT=35  
  -D ENCODER2_BUTTON=22 
  -D ENCODER3_CLK=26 
  -D ENCODER3_DT=25 
  -D ENCODER3_BUTTON=17 
  -D KNX_IP_WIFI
  ${KNX_IP.build_flags}
board = esp32dev
board_build.partitions=esp32_4mb.csv

[env:develop_ESP32_Sonos_NFC_Player_HSU]
extends = PN532_HSU, custom_ESP32, custom_develop, board_ESP32_Sonos_NFC_Player
build_flags =
  ${PN532_HSU.build_flags}
  #${ESP32_develop.build_flags} // need to much memory
  ${custom_ESP32.build_flags}
  ${custom_develop.build_flags}
  ${board_ESP32_Sonos_NFC_Player.build_flags}

; Release

[env:release_ESP32_Sonos_NFC_Player_HSU]
extends = PN532_HSU, custom_release_ESP32, custom_ESP32, board_ESP32_Sonos_NFC_Player
build_flags =
  ${PN532_HSU.build_flags}
  ${custom_release_ESP32.build_flags}  
  ${custom_ESP32.build_flags}
  ${board_ESP32_Sonos_NFC_Player.build_flags}
 

[env:release_ESP32_Sonos_NFC_Player_HSU_OTA]
extends = PN532_HSU, custom_release_ESP32, custom_ESP32, board_ESP32_Sonos_NFC_Player
build_flags =
  ${PN532_HSU.build_flags}
  ${custom_release_ESP32.build_flags}  
  ${custom_ESP32.build_flags}
  ${board_ESP32_Sonos_NFC_Player.build_flags}
  upload_protocol = espota
  upload_port=#192.168.0.28 # IP Address
